### ISSUE TITLE
อยากให้เพิ่มขั้นตอน npx vitepress init ใน Readme.md หน้าแรกสุด ก่อนจะ npm run 

### ISSUE THREAD

**Issue by SarahAHA121** [ThaiProgrammer/tpa-path#22]
พอดีลองติดตั้ง npm add -D vitepress แล้วไป npm run docs เลยตามที่เขียนใน readme.md ปัจจุบัน จะหาสคริปต์ docs ไม่เจอ
ต้อง init ก่อนด้วย npx vitepress init เลยเห็นไหนๆ ลงขั้นตอนย่อๆ ของการติดตั้ง vitepress แล้ว เลยอยากให้เพิ่ม

### จากนั้นตั้งค่าเริ่มต้น สร้างสคริปต์ VitePress 
```bash
npx vitepress init
```

เข้าไปด้วย จะได้สมบูรณ์ขึ้น ไม่ต้องเข้าไปที่ลิงค์รายละเอียดหลักอีกน่ะค่ะ <3
![image](https://github.com/user-attachments/assets/feaa4ed1-d624-4148-844d-7bb41a6ef46b)

**Comment by ponggun** [comment]
ได้เลยครับโผมมม

ขอบคุณมากๆนะครับ
