### ISSUE TITLE
เพิ่ม Code Refactoring ใน Practices > Coding Practices

### ISSUE THREAD

**Issue by RachaneeSaeng** [ThaiProgrammer/tpa-path#32]

**Comment by RachaneeSaeng** [comment]
See pull request https://github.com/ThaiProgrammer/tpa-path/pull/58

**Comment by ponggun** [comment]
@RachaneeSaeng Merged เรียบร้อยครับ สวยงาม

ขอบคุณมากๆนะครับ

![image](https://github.com/user-attachments/assets/4df9d5d9-15db-4aca-b76d-b5d82ff5d93d)
