### ISSUE TITLE
เพิ่ม Angular ใน Web Development Guidelines > Front End

### ISSUE THREAD

**Issue by nerometa** [ThaiProgrammer/tpa-path#49]

**Comment by nerometa** [comment]
Sent pull request #50

**Comment by nerometa** [comment]
### Angular 2nd revision + improvements

กระแสตอบรับดีแบบเกินคาดไม่ถึงตั้งแต่พี่ท่านนึงเอาไปลง facebook (ขอบคุณอีกครั้งนะครับ 🙏) เลยตัดสินใจ reopen issue ใหม่เพื่อปรับปรุงให้ดีขึ้นอีกครับ

#### QoL (Quality of Life) improvements
- [x] Code highlights จุดที่มีการแนะนำโค้ด เพื่อความสบายตาในการอ่านและหาโค้ดที่กำลังยกตัวอย่าง
- [x] ใส่ Emoji ธงชาติไทยกำกับ resource ที่เป็นภาษาไทย
- [x] ใส่ Emoji กำกับ resource ที่เป็นแหล่งรวม resource อีกที (index)

#### Fixes
- [x] แก้กลับไปใช้ title ปกติแทนการ access frontmatter (อาจต้องเปิดเป็นอีก issue ในอนาคต แต่เป็น minor bug)

#### Contents
- [x] เพิ่มรูปภาพและ diagram ในจุดที่สมควร
- [x] เพิ่มตัวอย่างเว็บไซต์และบริการ
- [x] เพิ่ม mini migration guide สำหรับอัปเดต Angular จากเก่าไปใหม่
- [x] เพิ่ม resource ใหม่ -> communities
- [x] เพิ่ม resource ใหม่ -> events and conferences
- [x] เพิ่ม resource ใหม่ -> libraries and tools > utilities
- [x] เพิ่ม resource ใหม่ -> libraries and tools > authentication
- [x] เพิ่มคอร์ส / คลิปสอน

**Comment by ponggun** [comment]
@nerometa  ขอบคุณมากๆเลยนะครับ ☺️🙏
